apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: nginx

# define um limite de réplicas de um Pod que podem ficar indisponíveis simultaneamente durante atualizações de nós (node drain) ou manutenções planejadas.