apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
  internalTrafficPolicy: Local # Evita que o balançador de tráfego distribua o tráfego interno para outras replicas do pod em outros node.
  externalTrafficPolicy: Cluster # Distribui o tráfego de entrada entre todas as replicas do pod, independentemente do node em que estão localizadas.
