apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubectl
  name: kubectl
spec:
  serviceAccountName: kubectl
  containers:
  - image: bitnami/kubectl
    name: kubectl
    command:
      - sleep
      - "9999999"