apiVersion: v1
kind: Secret
metadata:
  name: ssh-argocd-github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:fastech-team/gitops-k8s.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACA5rAN9J45KOi+0xHxmY2mbI9at9abYK5iBqNovMIbiWgAAAJioFi4HqBYu
    BwAAAAtzc2gtZWQyNTUxOQAAACA5rAN9J45KOi+0xHxmY2mbI9at9abYK5iBqNovMIbiWg
    AAAEBHWZydwhk2Mm4uQRWlPUq5CX+ZnhgUNeiDD63sQK41lzmsA30njko6L7TEfGZjaZsj
    1q31ptgrmIGo2i8whuJaAAAAEmFyZ29jZEBmYXN0ZWNoLmNvbQECAw==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"